### PR TITLE
Add support for multiple Puppet collections

### PR DESCRIPTION
**Pull request by MikaelSmith**
Updates the `puppet-agent` cask to track the `puppet` collection, which
is an alias to the latest versioned collection. Adds `puppet-agent-5`
and `puppet-agent-6` casks tracking the `puppet5` and `puppet6`
collections.

### CODE REVIEW

**Comment by slauger** [comment]
Hi,

i'm ok with the change. I mainly use the puppet-agent on my Mac for parsing puppet manifests locally (while developing new modules), so i always want the latest puppet release on my machine.

But would it be possible to add a default case for the MacOS.version switch statement with this change? I'm already on 10.14 and the puppet casks are currently not working with 10.14. 
```
Warning: Cask 'puppet-agent' is unreadable: undefined method `major_minor' for nil:NilClass
```
The default case could point to the most recent version.

**Comment by MikaelSmith** [comment]
Yeah, that's a problem I'll run into soon too. I'll see how I can clean it up.

**Comment by ragnarkon** [comment]
@MikaelSmith Change doesn't affect my workflow either.  I too just use Puppet for local testing, and thus almost always want the latest version.

The `else` statement is also good idea, but won't work until there is a 10.14 build due to the URL.

https://github.com/puppetlabs/homebrew-puppet/blob/ff0031a61b1892600f88a2c1c25340a4d143d42c/Casks/puppet-agent.rb#L12

**Comment by MikaelSmith** [comment]
Oh right, I'll have to be a bit smarter about it.
